---
- name: Deploy code.
  hosts: twincat_bsd
  vars:
    project_root: '{{ playbook_dir }}/../..'
    temp_dir: /tmp/sc-build
    install_dir: /usr/local/opt/areacontroller

  tasks:
    - name: Create or empty temporary directory
      file:
        path: '{{ temp_dir }}'
        state: '{{ item }}'
      loop: # delete then recreate to ensure it's empty - old source files cause problems
        - absent
        - directory

    - name: Ensure directories are present
      become: true
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: root
        group: areacontroller
        mode: u=rwx,g=rx,o=rx
        recurse: yes
      loop:
        - '{{ install_dir }}/etc/rc.d'
        - '{{ install_dir }}/static'
        - '{{ install_dir }}/bin'

    - name: Extract Go code
      ansible.builtin.unarchive:
        src: '/tmp/bsp-ew-build/area-controller.tar'
        dest: '{{ temp_dir }}/'

    - name: Build Go code - Area Controller
      ansible.builtin.command:
        chdir: '{{ temp_dir }}/area-controller'
        argv:
          - /usr/local/opt/go/bin/go
          - build
          - '-o'
          - '{{ temp_dir }}/areacontroller'
          - "./cmd/area-controller"
      environment:
        CGO_ENABLED: '1'
        CGO_CFLAGS: '-I/usr/local/include'
        CGO_LDFLAGS: '-L/usr/local/lib'

    - name: Build cmd/daylight-power
      ansible.builtin.command:
        chdir: '{{ temp_dir }}/area-controller'
        argv:
          - /usr/local/opt/go/bin/go
          - build
          - '-o'
          - '{{ temp_dir }}/daylight-power'
          - './cmd/daylight-power'
      environment:
        CGO_ENABLED: '1'
        CGO_CFLAGS: '-I/usr/local/include'
        CGO_LDFLAGS: '-L/usr/local/lib'

    - name: Install executables
      become: true
      ansible.builtin.copy:
        remote_src: yes
        src: '{{ temp_dir }}/{{ item }}'
        dest: '{{ install_dir }}/bin/{{ item }}'
        owner: root
        group: areacontroller
        mode: o=rwx,g=rx,o=rx
      loop:
        - 'areacontroller'
        - 'daylight-power'
