---
- name: Deploy configuration files.
  hosts: twincat_bsd
  vars:
    project_dir: "{{ playbook_dir }}/../.."
    deploy_src_dir: '{{ playbook_dir }}/..'
    install_dir: /usr/local/opt/areacontroller

  tasks:
    - name: Stop the services (if it exists)
      become: true
      ansible.builtin.service:
        name: "areacontroller"
        state: stopped

    - name: Ensure the rc.d directory is present
      become: true
      ansible.builtin.file:
        path: '{{ install_dir }}/etc/rc.d'
        state: directory
        recurse: yes
        owner: root
        group: areacontroller
        mode: u=rwX,g=rX,o=rX

    - name: Copy the rc scripts
      become: true
      ansible.builtin.copy:
        src: '{{ deploy_src_dir }}/freebsd/rc-script.sh'
        dest: '{{ install_dir }}/etc/rc.d/areacontroller'
        owner: root
        group: areacontroller
        mode: u=rwx,g=rx,o=rx

    - name: Make symlink for the rc script
      become: true
      ansible.builtin.file:
        path: "/usr/local/etc/rc.d/areacontroller"
        state: link
        src: '{{ install_dir }}/etc/rc.d/areacontroller'
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Ensure the data directory is present
      become: true
      ansible.builtin.file:
        path: '{{ install_dir }}/data'
        state: directory
        owner: areacontroller
        group: areacontroller
        mode: u=rwX,g=rX,o=

    - name: Copy the area controller config file
      become: true
      ansible.builtin.copy:
        src: '{{ project_dir }}/config/{{ floor }}/area-controller.local.json'
        dest: '{{ install_dir }}/data/area-controller.local.json'
        owner: root
        group: areacontroller
        mode: u=rw,g=r,o=r

    - name: Copy the daylight-power config file
      become: true
      ansible.builtin.copy:
        src: '{{ project_dir }}/config/{{ floor }}/daylight-power.json'
        dest: '{{ install_dir }}/etc/daylight-power.json'
        owner: root
        group: areacontroller
        mode: u=rw,g=r,o=r

    - name: Set daemon flags
      become: true
      community.general.sysrc:
        name: areacontroller_flags
        state: present
        value: "-data-dir {{ install_dir }}/data -static-dir {{ install_dir }}/static -listen-https :8443"

    - name: Enable log rotation for the areacontroller service
      become: true
      block:
        - name: Ensure newsyslog config directory present
          ansible.builtin.file:
            path: '/usr/local/etc/newsyslog.conf.d'
            state: directory
            owner: root
            mode: u=rwX,g=rX,o=rX

        - name: Copy newsyslog config file
          ansible.builtin.copy:
            src: '{{ deploy_src_dir }}/freebsd/newsyslog.conf.d/areacontroller.conf'
            dest: '/usr/local/etc/newsyslog.conf.d/areacontroller.conf'
            owner: root
            mode: u=rw,g=r,o=r

    - name: "{{ areacontroller_enabled | bool | ternary('Enable and start', 'Disable and stop') }} areacontroller service"
      become: true
      ansible.builtin.service:
        name: areacontroller
        state: "{{ areacontroller_enabled | bool | ternary('started', 'stopped') }}"
        enabled: "{{ areacontroller_enabled | bool }}"

    - name: Ensure daylight-power log file present
      become: true
      ansible.builtin.file:
        path: /var/log/daylight-power.log
        state: touch
        owner: Administrator

    - name: Remove old cron jobs
      become: true
      ansible.builtin.cron:
        user: Administrator
        state: absent
        name: '{{ item }}'
      loop:
        - 'Power Off Lights (night)'
        - 'Test On'
        - 'Test Low'
        - 'Test Off'
        - 'Test Config on'
        - 'Test Config off'

    - name: Add cron jobs for daylight-power
      become: true
      ansible.builtin.cron:
        user: Administrator
        disabled: "{{ daylight_power_cron_enabled | bool | ternary('no', 'yes') }}"
        name: '{{ item.name }}'
        hour: '{{ item.hour }}'
        minute: '{{ item.minute }}'
        job: '/usr/local/opt/areacontroller/bin/daylight-power -dali /usr/local/opt/areacontroller/etc/daylight-power.json -level {{ item.level }} 2>&1 >> /var/log/daylight-power.log'
      loop:
        - name: Power On Lights
          hour: 6
          minute: 0
          level: 100
        - name: Power Off Lights
          hour: '19-23,23,0-5'
          minute: '*/5'
          level: 0
      notify: Restart cron

  handlers:
    - name: Restart cron
      become: true
      ansible.builtin.service:
        name: cron
        state: restarted