---
- name: Deploy configuration files.
  hosts: twincat_bsd
  vars:
    project_dir: "{{ playbook_dir }}/../.."
    deploy_src_dir: '{{ playbook_dir }}/..'
    install_dir: /usr/local/opt/areacontroller

    areacontroller_enabled: no
    daylight_power_cron_enabled: yes

  tasks:
    - name: Stop the services (if it exists)
      become: true
      ansible.builtin.service:
        name: "areacontroller"
        state: stopped

    - name: Ensure the rc.d directory is present
      become: true
      ansible.builtin.file:
        path: '{{ install_dir }}/etc/rc.d'
        state: directory
        recurse: yes
        owner: root
        group: areacontroller
        mode: u=rwX,g=rX,o=rX

    - name: Copy the rc scripts
      become: true
      ansible.builtin.copy:
        src: '{{ deploy_src_dir }}/freebsd/rc-script.sh'
        dest: '{{ install_dir }}/etc/rc.d/areacontroller'
        owner: root
        group: areacontroller
        mode: u=rwx,g=rx,o=rx

    - name: Make symlink for the rc script
      become: true
      ansible.builtin.file:
        path: "/usr/local/etc/rc.d/areacontroller"
        state: link
        src: '{{ install_dir }}/etc/rc.d/areacontroller'
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Ensure the data directory is present
      become: true
      ansible.builtin.file:
        path: '{{ install_dir }}/data'
        state: directory
        owner: areacontroller
        group: areacontroller
        mode: u=rwX,g=rX,o=

    - name: Copy the area controller config file
      become: true
      ansible.builtin.copy:
        src: '{{ project_dir }}/config/{{ floor }}/area-controller.local.json'
        dest: '{{ install_dir }}/data/area-controller.local.json'
        owner: root
        group: areacontroller
        mode: u=rw,g=r,o=r

    - name: Copy the daylight-power config file
      become: true
      ansible.builtin.copy:
        src: '{{ project_dir }}/config/{{ floor }}/daylight-power.json'
        dest: '{{ install_dir }}/etc/daylight-power.json'
        owner: root
        group: areacontroller
        mode: u=rw,g=r,o=r

    - name: Set daemon flags
      become: true
      community.general.sysrc:
        name: areacontroller_flags
        state: present
        value: "-data-dir /usr/local/opt/areacontroller/data -static-dir /usr/local/opt/areacontroller/static -listen-https :8443"

    - name: Enable and start areacontroller service
      become: true
      ansible.builtin.service:
        name: areacontroller
        state: "{{ areacontroller_enabled | bool | ternary('started', 'stopped') }}"
        enabled: "{{ areacontroller_enabled | bool }}"

    - name: Add cron jobs for daylight-power
      become: true
      ansible.builtin.cron:
        user: Administrator
        disabled: "{{ daylight_power_cron_enabled | bool | ternary('no', 'yes') }}"
        name: '{{ item.name }}'
        hour: '{{ item.hour }}'
        minute: '{{ item.minute }}'
        job: '/usr/local/opt/areacontroller/bin/daylight-power -dali /usr/local/opt/areacontroller/etc/daylight-power.json -level {{ item.level }} 2>&1 >> /var/log/daylight-power.log'
      loop:
        - name: Power On Lights
          hour: 6
          minute: 0
          level: 90
        - name: Power Off Lights
          hour: 19
          minute: 0
          level: 0
        - name: Test Low
          hour: 13
          minute: 57
          level: 70
        - name: Test On
          hour: 13
          minute: 59
          level: 90
      notify: Restart cron

  handlers:
    - name: Restart cron
      become: true
      ansible.builtin.service:
        name: cron
        state: restarted