---
- name: Prepare system for ansible
  hosts: twincat_bsd
  gather_facts: false
  become: true
  become_method: doas
  tasks:
    # it's necessary to perform an upgrade of pkg at least once before enabling the FreeBSD repo
    - name: Upgrade pkg
      raw: "pkg install -y pkg"

    - name: Enable the upstream FreeBSD package repository.
      raw: "sed -i.bak 's/enabled: no/enabled: yes/' /usr/local/etc/pkg/repos/FreeBSD.conf"

    - name: Install python.
      raw: "pkg install -y python"

- name: Update packages & install dependencies
  hosts: twincat_bsd
  become: true
  tasks:
    - name: Update packages
      community.general.pkgng:
        name: '*'
        state: latest

    - name: Install system utilities.
      community.general.pkgng:
        name:
          - rsync
          - wget
          - gtar
        state: present

    - name: Install application dependencies.
      community.general.pkgng:
        name:
          - os-generic-userland-devtools
        state: present

    - name: Create opt directory for custom installed software
      ansible.builtin.file:
        path: /usr/local/opt
        state: directory
        owner: root
        group: wheel
        mode: 0755

    - name: Download Go compiler
      become: false
      ansible.builtin.get_url:
        url: 'https://go.dev/dl/go1.19.2.freebsd-amd64.tar.gz'
        dest: '/tmp/go.tar.gz'
        checksum: sha256:d74c88430484d14826ec21161e3b9336bd021f502b6594c4dd00e9ec730ee51d
      register: download_go

    - name: Extract Go compiler
      when: download_go.changed
      ansible.builtin.unarchive:
        remote_src: true
        src: '/tmp/go.tar.gz'
        dest: /usr/local/opt/
        owner: root
        group: wheel
        mode: u=rwX,g=rX,o=rX

- name: Prepare daemon user and group
  hosts: twincat_bsd
  become: true
  tasks:
    - name: Create twincat group.
      ansible.builtin.group:
        name: twincat
        state: present
        system: yes

    - name: Add Administrator to the twincat group
      ansible.builtin.user:
        name: Administrator
        append: yes
        groups:
          - twincat

    - name: Create areacontroller user.
      ansible.builtin.user:
        name: areacontroller
        state: present
        groups: twincat
        create_home: no
        home: /usr/local/opt/areacontroller
        shell: /sbin/nologin

    - name: Prepare areacontroller directory
      ansible.builtin.file:
        path: /usr/local/opt/areacontroller
        state: directory
        owner: root
        group: areacontroller
        mode: 0755

- name: Operating system configuration
  hosts: twincat_bsd
  become: true
  tasks:
    - name: Make the tcpaldrv device owned by the twincat group
      ansible.builtin.blockinfile:
        path: /etc/devfs.conf
        block: |
          own   tcpaldrv    root:twincat
          perm  tcpaldrv    0660
      notify: Restart devfs

    - name: Open firewall ports
      ansible.builtin.blockinfile:
        path: /etc/pf.conf
        block: |
          # Allow access to Smart Core
          pass in quick proto tcp to port 23557 keep state
          # Allow access to the Web UI & grpc-web
          pass in quick proto tcp to port 8443 keep state
          # Allow BACnet packets
          pass in quick proto udp to port 47808
      notify: Restart pf

    - name: Set static IP on X001
      community.general.sysrc:
        name: ifconfig_igb0
        state: present
        value: 'inet {{ x001_ip }} netmask 255.255.255.0'
      notify: Restart network

  handlers:
    - name: Restart devfs
      ansible.builtin.service:
        name: devfs
        state: restarted

    - name: Restart pf
      ansible.builtin.service:
        name: pf
        state: restarted

    - name: Restart network
      ansible.builtin.service:
        name: '{{ item }}'
        state: restarted
      loop:
        - netif
        - routing
