---
- name: Use USB Drive as TCBSD repository source
  hosts: twincat_bsd
  become: true
  tasks:
    - name: Create mount point
      ansible.builtin.file:
        path: /mnt/usb
        state: directory

    - name: Mount USB drive on /mnt/usb
      ansible.posix.mount:
        boot: no
        fstype: msdosfs
        path: /mnt/usb
        src: /dev/da0s1
        state: mounted

    - name: Switch repo
      ansible.builtin.replace:
        backup: yes
        path: /etc/pkg/TCBSD.conf
        regexp: 'url:\s*"[^"]*"'
        replace: 'url: "file:///mnt/usb/TcBSD/TCBSD/13/stable/packages"'